before_install:
  - sudo apt-get update
  - sudo apt-get -y install libusb-1.0-devel

language: rust

rust:
  - stable

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

#jobs:
#  allow_failures:
#    - rust: stable
#  fast_finish: true
#
#cache: cargo